version: '3.8'

services:
  # 開発環境
  app-dev:
    build:
      context: .
      target: development
    ports:
      - "3001:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_EXCHANGE_RATE_API_KEY=${NEXT_PUBLIC_EXCHANGE_RATE_API_KEY}
    stdin_open: true
    tty: true
    networks:
      - app-network
    restart: unless-stopped

  # 本番環境
  app-prod:
    build:
      context: .
      target: production
    ports:
      - "3002:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_EXCHANGE_RATE_API_KEY=${NEXT_PUBLIC_EXCHANGE_RATE_API_KEY}
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge 